//register new user types
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';

//login user types
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';


//check user login types
export const CHECK_LOGIN_REQUEST = 'CHECK_LOGIN_REQUEST';
export const CHECK_LOGIN_SUCCESS = 'CHECK_LOGIN_SUCCESS';
export const CHECK_LOGIN_FAIL = 'CHECK_LOGIN_FAIL';


//logout user
export const LOGOUT_USER = 'LOGOUT_USER';


//check user login types
export const GET_CURRENET_USER_REQUEST = 'GET_CURRENET_USER_REQUEST';
export const GET_CURRENET_USER_SUCCESS = 'GET_CURRENET_USER_SUCCESS';
export const GET_CURRENET_USER_FAIL = 'GET_CURRENET_USER_FAIL';


//get weather from weather api
export const GET_WEATHER_REQUEST = 'GET_WEATHER_REQUEST';
export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS';
export const GET_WEATHER_FAIL = 'GET_WEATHER_FAIL';

//clear collected weather data
export const CLEAR_WEATHER_DATA = 'CLEAR_WEATHER_DATA';

//save collected weather data to DB
export const GET_WEATHER_HISTORY_REQUEST = 'GET_WEATHER_HISTORY_REQUEST';
export const GET_WEATHER_HISTORY_SUCCESS = 'GET_WEATHER_HISTORY_SUCCESS';
export const GET_WEATHER_HISTORY_FAIL = 'GET_WEATHER_HISTORY_FAIL';


//get previous weather query detais data from DB
export const GET_WEATHER_DETAILS_REQUEST = 'GET_WEATHER_DETAILS_REQUEST';
export const GET_WEATHER_DETAILS_SUCCESS = 'GET_WEATHER_DETAILS_SUCCESS';
export const GET_WEATHER_DETAILS_FAIL = 'GET_WEATHER_DETAILS_FAIL';


//update current user info in DB
export const UPDATE_CURRENT_USER_REQUEST = 'UPDATE_CURRENT_USER_REQUEST';
export const UPDATE_CURRENT_USER_SUCCESS = 'UPDATE_CURRENT_USER_SUCCESS';
export const UPDATE_CURRENT_USER_FAIL = 'UPDATE_CURRENT_USER_FAIL';